import "../styles/globals.css";
import { Fragment } from "react";
import "antd/dist/antd.css";
import "tailwindcss/tailwind.css";
import { ApolloProvider } from "@apollo/client";
import { client } from "../lib/apolloSetup";
import Head from "next/head";
import NextNprogress from "nextjs-progressbar";

function MyApp({ Component, pageProps }: any) {
  const Layout =
    Component.getLayout ||
    ((props: any) => <Fragment>{props.children}</Fragment>);
  return (
    <ApolloProvider client={client}>
      <NextNprogress />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </ApolloProvider>
  );
}

export default MyApp;
