import { Fragment } from 'react'
import DefaultLayout from '../layouts/default'
import Head from 'next/head'


const Home: any = () => {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Fragment>
  )
}

Home.getLayout = DefaultLayout

export default Home
